runtime: nodejs16

beta_settings:
cloud_sql_instances: newkoo0901:us-central1:princekook


env_variables:
   DB_USER: masterjk
   DB_PASS: jk1234
   DB_NAME: prince_data
   # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
   CLOUD_SQL_CONNECTION_NAME: newkoo0901:us-central1:princekook

